In [ ]:
# YAZ KAMPI: VERİ BİLİMİNE GİRİŞ EĞİTİMİ
# PYTHON ÖDEVİ 3
# İpek Nur Ercan

In [3]:
# soru1
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

# Tekrar eden notları sil
benzersiz = list(set(notlar))

# En yüksek ve en düşük not
en_yuksek = max(notlar)
en_dusuk = min(notlar)

# Küçükten büyüğe sıralama
sirali = sorted(benzersiz)

print("Benzersiz liste:", benzersiz)
print("En yüksek not:", en_yuksek)
print("En düşük not:", en_dusuk)
print("Sıralı liste:", sirali)


Benzersiz liste: [100, 92, 85, 76]
En yüksek not: 100
En düşük not: 76
Sıralı liste: [76, 85, 92, 100]


In [2]:
# soru2
def armstrong_mu(sayi):
    toplam = sum(int(hane) ** 3 for hane in str(sayi))
    return toplam == sayi

print(153, "Armstrong mu?", armstrong_mu(153))
print(123, "Armstrong mu?", armstrong_mu(123))


153 Armstrong mu? True
123 Armstrong mu? False


In [4]:
# soru3
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

# Ortak elemanlar
ortak = A & B

# Sadece A’da olanlar
sadece_A = A - B

# Birleşim (alfabetik)
birlesim = sorted(A | B)

print("Ortak diller:", ortak)
print("Sadece A:", sadece_A)
print("Birleşim:", birlesim)


Ortak diller: {'Python', 'SQL'}
Sadece A: {'R', 'Java'}
Birleşim: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [5]:
# soru4
import random, statistics

sayilar = [random.randint(1, 100) for _ in range(10)]

ortalama = statistics.mean(sayilar)
std = statistics.stdev(sayilar)

print("Sayılar:", sayilar)
print("Ortalama:", ortalama)
print("Standart sapma:", std)



Sayılar: [98, 23, 81, 97, 57, 33, 99, 97, 68, 63]
Ortalama: 71.6
Standart sapma: 27.845606076682508


In [7]:
# soru5
from collections import Counter

def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    en_sik = Counter(kelimeler).most_common(1)[0][0]
    return toplam, en_uzun, en_sik

metin = "veri bilimi dersindeki veri bilimi öğrencilerinin veri bilgisi verisi"
print(kelime_sayaci(metin))


(9, 'öğrencilerinin', 'veri')


In [8]:
# soru6
sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = list(filter(lambda x: x % 2 == 0, sayilar))
kareler = list(map(lambda x: x**2, ciftler))
sirali = sorted(kareler, reverse=True)

print("Çiftler:", ciftler)
print("Kareler:", kareler)
print("Azalan sıralı kareler:", sirali)


Çiftler: [12, 18, 24, 16]
Kareler: [144, 324, 576, 256]
Azalan sıralı kareler: [576, 324, 256, 144]


In [9]:
# soru7
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sirali = sorted(kelimeler, key=lambda x: len(x))

print(sirali)


['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [10]:
# soru8
def rakam_toplami(metin):
    import re
    sayilar = re.findall(r"\d+", metin)  # tüm sayıları bul
    return sum(map(int, sayilar))

print(rakam_toplami("abc12def3"))  # 15


15


In [11]:
# soru9
import numpy as np

dizi = np.random.randint(0, 51, 10)
print("Dizi:", dizi)
print("Ortalama:", np.mean(dizi))
print("Standart sapma:", np.std(dizi))
print("En büyük:", np.max(dizi))


Dizi: [15  1  1 23 49 35 44  1 25  4]
Ortalama: 19.8
Standart sapma: 17.434448657758008
En büyük: 49


In [12]:
# soru10
import numpy as np

matris = np.random.rand(5, 5)
sutun_ort = np.mean(matris, axis=0)
binary = (matris > 0.5).astype(int)

print("Matris:\n", matris)
print("Sütun ortalamaları:", sutun_ort)
print("Binary matris:\n", binary)


Matris:
 [[0.22510115 0.29585958 0.87256165 0.8158918  0.94946729]
 [0.80652947 0.55075114 0.07129345 0.69867184 0.83731287]
 [0.10024441 0.25958698 0.37915755 0.12337584 0.29973687]
 [0.85439377 0.69231091 0.59750675 0.09631716 0.13998983]
 [0.2058303  0.87238822 0.65241217 0.78839868 0.9857133 ]]
Sütun ortalamaları: [0.43841982 0.53417937 0.51458631 0.50453106 0.64244403]
Binary matris:
 [[0 0 1 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 1 0 0]
 [0 1 1 1 1]]
